services:
  backend:
    image: 169136975305.dkr.ecr.eu-west-2.amazonaws.com/ncs-hs-backend:latest
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__PostgreSql: Host=postgres;Port=5432;Database=pbes;Username=postgres;Password=Yange@junior1
      Ollama__BaseUrl: http://host.docker.internal:11434
      Ollama__Model: llama3.2-vision
      Ollama__TextModel: llama3:8b
      Ollama__TimeoutSeconds: "300"
    depends_on:
      - postgres

  frontend:
    image: 169136975305.dkr.ecr.eu-west-2.amazonaws.com/ncs-hs-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  gateway:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pbes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Yange@junior1
    volumes:
      - pbes_pgdata:/var/lib/postgresql/data

volumes:
  pbes_pgdata:
